config/routes.rb
Rails.application.routes.draw do



  root "users#index"

  resources :users do 
    resources :reviews, :only => [:index, :show]
  end

  resources :schools do 
    resources :reviews
    resources :bookmarks, only: [:create, :update, :destroy]
  end

  resource :session, :only => [:new, :create, :destroy]
  resources :schools, only: [:index, :show]
  resources :comparisons, :only => [:index]

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"


end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :username,
            :presence => true

  validates :password,
            :length => { :in => 8..24 },
            :allow_nil => true

  validates :email,
            :presence => true,
            :uniqueness => true


  has_many :reviews

  has_many :bookmarks
  has_many :schools, through: :bookmarks
  has_many :reviews, class_name: "Review", foreign_key: :user_id

  # after_create :send_welcome_email

  private

  # def send_welcome_email
  #   UserMailer.welcome(self).deliver!
  # end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, :only => [:index, :new, :create]
  before_action :require_current_user, :only => [:edit, :update, :destroy, :show]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] = "User created."
      redirect_to @user
    else
      flash.now[:danger] = "User not created. Error."
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "User updated."
      redirect_to @user
    else
      flash.now[:danger] = "User not updated. Error."
      render :edit
    end
  end

  def show
    @user = current_user
  end

  def destroy
    @user = current_user
    if @user.delete
      sign_out
      flash[:success] = "User deleted."
      redirect_to root_url
    else
      flash[:danger] = "User not deleted. Error."
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def edit_button
    link_to "Edit User", edit_user_path(current_user), class: "btn btn-primary" if current_user == @user
  end

end

app/views/users/_application_timeline.html.erb
<h3>September-October</h3>
<ul>
  <li>
    <span class="bold">Register for the <%= link_to "SAT", "https://collegereadiness.collegeboard.org/sat/register" %> and/or <%= link_to "ACT", "https://www.act.org/content/act/en/products-and-services/the-act/registration-information.html" %></span>. Or find out if the school you're interested in is <%=link_to "test-optional", "http://www.fairtest.org/university/optional" %>
  </li>
  <li>
    <span class="bold">Prepare and/or revise application essays.</span> Share your essays with parents and close friends. Make sure your voice comes out and of course, check for typos!
  </li>
  <li>
    <span class="bold">Ask for letters of recommendation.</span> Reach out to teachers who know you well and can speak to your strengths as a student. Be sure to give them plenty of notice so they can write you a good letter.
  </li>
</ul>

<h3 class="subgroup">November-December</h3>
<ul>
  <li>
    <span class="bold">Submit early decision or early action applications, if desired.</span> Early Decision deadlines are usually in November. Early action may have multiple rounds.
  </li>
   <li>
    <span class="bold">Submit regular decision applications.</span>Many Regular Decision deadlines are January 1st.
  </li>
  <li>
    <span class="bold">Send your SAT and/or ACT scores to schools where you are applying.</span>
  </li>
  <li>
    <span class="bold">Send transcripts to schools where you are applying.</span>
  </li>
  <li>
    <span class="bold">Submit the <%= link_to "CSS profile", "https://student.collegeboard.org/css-financial-aid-profile" %>.</span>
  </li>
</ul>

<h3 class="subgroup">January</h3>
<ul>
  <li>
    <span class="bold">Complete the <%= link_to "FAFSA", "https://fafsa.ed.gov/" %>.</span> The FAFSA is the main determinant of your federal financial aid and can be completed after January 1 of your senior year.
  </li>
   <li>
    <span class="bold">Compare award letters.</span>
  </li>
</ul>

<h3 class="subgroup">March/April</h3>
<ul>
  <li>
    <span class="bold">Review acceptance letters.</span> Ask schools questions. This is where you will be for the next 4 years!
  </li>
   <li>
    <span class="bold">Decide!</span>
  </li>
</ul>

app/views/users/_checklist.html.erb
<tr>
  <%= simple_form_for [school, bookmark] do |bookmark_fields| %>
  <td><%= link_to school.school_name, school %></td>
  <td><%= bookmark_fields.input :essay, label: false %></td>
  <td><%= bookmark_fields.input :letters, label: false %></td>
  <td><%= bookmark_fields.input :application, label: false %></td>
  <td><%= bookmark_fields.submit "Update Status", class:"btn btn-primary" %>
  <% end %>
  <td><%= button_to "Remove School", school_bookmark_path(school.id, bookmark.id), method: :delete, class:"btn btn-danger" %></td>
</tr>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
      
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.button :submit %>

<% end %>

app/views/users/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 header-container">
      <p class="title-name"> <%= @user.username %>  <%= edit_button %></p>
    </div>
  </div>
</div>

app/views/users/_search_bar.html.erb
  <%= form_tag schools_path, :method => 'get' do %>
    <br>
    <div class="form-group">

      <div class="col-xs-11 col-xs-offset-1 col-xs-pull-1">
        <%= label_tag "query[school_name]", "Search by School" %>
        <%= text_field_tag "query[school_name]", "", placeholder: "University of Washington", class: "form-control" %>
      </div>
    </div>
    <br>

    <div class="form-group">
      <div class="col-sm-4">

      <%= label_tag "query[school_region_id]", "Region:", class: " top-margin"%>
      <%= select_tag("query[school_region_id]", options_for_select(school_regions), multiple: true, class: "form-control" , )%>
      </div>
    </div>
    <br>

    <div class="form-group">
      <div class="col-sm-3">

    <%= label_tag "query[school_locale]", "Locale:", class: " top-margin" %>
    <%= select_tag("query[school_locale]", options_for_select(locale_types), multiple: true, class: "form-control") %>
    <br>

      </div>
    </div>

    <div class="col-sm-2">
      <div class="form-group">
        <div class="row">
          <div class="col-sm-12">
            <%= label_tag :sort, "Sort By:", class: "top-margin" %>
            <%= select_tag :sort, options_for_select([['Cost In State', 'cost_in_state'],
                                                      ['Cost Out of State', 'cost_out_state'],
                                                      ['Size', 'size'],
                                                      ['Selectivity', 'selectivity'],
                                                      ['SAT Scores', 'sat_score']]) %>
          </div>
        </div>
      </div>
      <div class="form-group">
          <%= label_tag "Ascending:", "Ascending:", class: "inline-block" %>
          <%= radio_button_tag 'order', 'ASC', class: "inline-block" %>

      <%= label_tag "Descending:"%>
      <%= radio_button_tag 'order', 'DESC' %>
      </div>
      <br>
    </div>
    <div class="col-sm-1">
      <%= submit_tag "Search!", class: "btn btn-success btn-lg", id: "search-button" %>
    </div>
  <% end %>
</div>

app/views/users/_timeline_chart.html.erb
<%= timeline [
  ["Register For SAT", "2016-09-01", "2016-10-31"],
  ["Prepare and/or revise application essays", "2016-09-01", "2016-10-31"],
  ["Ask for letters of recommendation", "2016-09-01", "2016-10-31"],
  ["Submit early decision or early action applications, if desired", "2016-10-15", "2016-11-31"],
  ["Submit regular decision applications", "2016-10-31", "2016-12-31"],
  ["Send your SAT and/or ACT scores to schools where you are applying.", "2016-10-31", "2016-11-30"],
  ["Send transcripts to schools where you are applying.", "2016-10-31", "2016-12-31"],
  ["Submit the CSS profile.", "2016-11-30", "2016-12-31"],
  ["Complete the FAFSA", "2016-12-15", "2017-01-31"],
  ["Compare award letters.", "2016-12-15", "2017-02-20"],
  ["Get Acceptances!", "2017-02-15", "2017-04-30"]
] , height: "550px" %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      
      <h1>Update User</h1>

      <%= render partial: "form", locals: {user: @user} %>
      <br>
      <%= button_to "Delete User", user_path(current_user), method: :delete %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="jumbotron">

  <div class="row">
    <div class="col-sm-12">

      <h1>Welcome to App.ly</h1>
      <br>
      <h3>Your Complete Guide to Applying to College</h3>
      <% unless current_user %>
      	<%= link_to "Sign up!", new_user_path, class: "btn btn-primary btn-lg", id: "new-user-button" %>
      <% end %>

    </div>
    <%= render "search_bar" %>
  </div>

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 newuser">
      
      <h1>Create a New User</h1>

      <%= render partial: "form", locals: {user: @user} %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "header", locals: {user: @user} %>

  <div class="row">
    <!-- sidebar -->
    <div class="col-sm-4">
      <div class="info-box fixed">
        <h3>Application Timeline</h3>
        <%= render partial: 'users/application_timeline' %>
      </div>
    </div>


    <div class="col-sm-8">
      <% if @user.schools.empty? %>
        <div class="col-sm-12 info-box">
            <h3>You have no schools saved to your list</h3>
            <h5>Start your list by searching for schools</h5>
            <%= render "search_bar" %>
            
        </div>
      <% else %>
        <div class="col-sm-12 info-box">
          <div class="school-list">
            <h3>Your Schools and Application Checklist</h3>
            <div class="table-responsive">
              <table class="table table-striped table-hover table-condensed"
                <tr>
                  <th>School</th>
                  <th>Essay Written?</th>
                  <th>Letters of Recommendation Written?</th>
                  <th>Application Sent?</th>
                  <th></th>
                  <th></th>
                </tr>
                <% @user.schools.each do |school| %>
                  <%= render partial: "checklist", locals: {school: school, bookmark: Bookmark.where("user_id = ? AND school_id = ?", @user.id, school.id).first} %>
                <% end %>
              </table>
            </div>
          </div>
        </div>

        <div class="col-sm-12">
          <ul class="nav nav-tabs">
            <li class="active"><a  href="#compare" data-toggle="tab">Compare Schools</a></li>
            <li><a href="#reviews" data-toggle="tab">Your Reviews</a></li>
          </ul>

          <div class="tab-content ">
            <div class="tab-pane active" id="compare">
              <div class="info-box">
                <h3>Compare Your Schools</h3>
                <h5>Choose up to 5 of your schools for in-depth comparison:</h5>
                <div class="comparison-box">
                  <%= form_tag comparisons_path, :method => 'get' do %>
                    <%= select_tag("schools", options_for_select(bookmarked_schools(@user.schools)), multiple: true) %><br>
                    <%= submit_tag "See Comparison", class:"btn btn-primary" %>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="tab-pane" id="reviews">
              <div class="info-box">
                <h3>Your Reviews</h3>
                <ul>
                <% @user.reviews.each do |review| %>
                  <li> <span><%= link_to review.school.school_name, school_path(review.school) %></span> | 
                             <%= review.body %> 
                             <%= link_to "Edit", edit_school_review_path(review.school, review) %> </li>
                <% end %>
                </ul>
              </div>
            </div>
          </div>
          <div class='info-box'>
            <h3>Application Timeline</h3>
            <%= render "timeline_chart" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>