config/routes.rb
Rails.application.routes.draw do



  root "users#index"

  resources :users do 
    resources :reviews, :only => [:index, :show]
  end

  resources :schools do 
    resources :reviews
    resources :bookmarks, only: [:create, :update, :destroy]
  end

  resource :session, :only => [:new, :create, :destroy]
  resources :schools, only: [:index, :show]
  resources :comparisons, :only => [:index]

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"


end

app/models/school.rb
require 'rubygems'
require 'bundler/setup'
require 'mechanize'
class School < ActiveRecord::Base
  has_one :academic, dependent: :destroy
  has_one :admission, dependent: :destroy
  has_one :aid, dependent: :destroy
  has_one :completion, dependent: :destroy
  has_one :cost, dependent: :destroy
  has_one :earning, dependent: :destroy
  has_one :repayment, dependent: :destroy
  has_one :student, dependent: :destroy

  has_many :reviews

  has_many :bookmarks

  has_many :users, through: :bookmarks

  def get_map_url
    response = get_coords_from_location
		"https://maps.googleapis.com/maps/api/staticmap?center=#{response["lat"]},#{response["lng"]}&zoom=15&size=400x400&key=AIzaSyDTLUeLPMNZy4Gw99gQNFF6d1gyDbukKmg"

  end

  def get_street_view
    response = get_coords_from_location
    "https://maps.googleapis.com/maps/api/streetview?size=400x400&location=#{response["lat"]},#{response["lng"]}&fov=90&heading=235&pitch=10&key=AIzaSyDzAzsvsSRGmqNCzBALyd8ISPylRAn5-mg"
  end

  def get_coords_from_location
    url = "https://maps.googleapis.com/maps/api/geocode/json?address=#{urlify(school_name)},#{urlify(location)}&key=AIzaSyBi_LAVQdQK86p7BcCxTxYuPr1lKVC5HAw"
     response = HTTParty.get(url, verify: false)["results"]
    if response.empty?
      return { "lat" => 34.138792, "lng" => -118.125407 }
    else
      return response.first["geometry"]["location"]
    end
  end

  def urlify(location)
    location.gsub(" ", "+")
  end

	def location
   "#{school_city}, #{school_state}"
	end


	def urlify(location)
   location.gsub(" ", "+")
	end


	def popular_subjects
   attribs = academic.attributes
   attribs = attribs.delete_if { |k, v| k == "created_at" || k == "school_id" || k == "updated_at" || k == "id" }
   attribs = attribs.sort_by { |subject, percent| percent }.reverse[0..9].to_h
   attrib_keys = attribs.map do |k, v|
     k.gsub("program_percentage_", "")
     k.gsub("_", " ")
     k.titleize
   end
   attrib_keys.zip(attribs.values).to_h
	end

  def self.index_search(params)
    if params['school_name']
      school_name = params['school_name']
    end
    if params['school_region_id']
      region_ids = params['school_region_id'].map(&:to_i)
    end
    if params['school_locale']
      school_locales = params['school_locale'].map(&:to_i)
      school_locales.map! { |l| [l, l-1, l-2]}.flatten!
    end

    query = fuzzy_search_school(school_name) if school_name
    if query && school_locales
      query = query.where_school_locale_equals(school_locales)
    elsif school_locales
      query = where_school_locale_equals(school_locales)
    end
    if query && region_ids
      query = query.where_region_id_equals(region_ids)
    elsif region_ids
      query = where_region_id_equals(region_id)
    end
    query
  end

  def self.where_school_locale_equals(school_locales)
    where(school_locale: school_locales)
  end

  def self.where_region_id_equals(region_ids)
    where(school_region_id: region_ids)
  end

  def self.fuzzy_search_school(query)
    query = '%' + query + '%'
    where("school_name ILIKE ?", query)
  end
end



# queries = query.split(' ').map { |q| '%' + q + '%' }
# result = nil
# queries.each do |q|
#   if result.nil?
#     where("school_name ILIKE ?", q)
#   else
#     result.where("school_name ILIKE ?", q)
#   end
# end
# result

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  skip_before_action :require_login

  def index
    @query = School.index_search(query_params)
    if params[:sort]
      options = [params[:sort], params[:order]]
      @query = sort_by(@query, options)
    end
    @schools = @query
  end

  def show
    @school = School.find(params[:id])
    @restaurants = YelpAPI.new.get_top_ten(@school).businesses
  end

  private

  def query_params
    params.permit(:utf8, :commit, query: [:school_name, school_region_id: [], school_locale: []])[:query]
  end

  def region_numbers(regions)
    regions.map(&:to_i)
  end

  def sort_by(query, options)
    # sanitizing inputs
    order = options[1] == 'ASC' ? 'ASC' : 'DESC'
    case options[0]
    when 'cost_in_state'
      query.joins(:cost).order("tuition_in_state #{order}")
    when 'cost_out_state'
      query.joins(:cost).order("tuition_out_of_state #{order}")
    when 'size'
      query.joins(:student).order("size #{order}")
    when 'selectivity'
      query.joins(:admission).order("admission_rate_overall #{order}")
    when 'sat_score'
      query.joins(:admission).order("sat_scores_average_overall #{order}")
    end
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
	
	def get_aid_info(school)
		attribs = school.aid.attributes.delete_if { |k,v| k == "school_id" || k == "id" || k == "created_at" || k == "updated_at"}
	end

  def get_aid_keys(school)
    keys = school.aid.attributes.keys.delete_if {|k| k == "school_id" || k == "id" || k == "created_at" || k == "updated_at"}
  end

  def get_academic_keys(school)
    keys = school.academic.attributes.keys.delete_if {|k| k == "school_id" || k == "id" || k == "created_at" || k == "updated_at"}
  end

  def to_percent(value)
    if value.nil?
      "N/A"
    else
      "#{(value*100).round(1)}%"
    end
  end

  def subject_name(subject)
    subject.split(" ")[2..-1].join(" ")
  end

  def float_to_int(f)
    if f
      f.to_i
    else
      ""
    end
  end


  def get_demographic_data(school)
    data = {}
    data["White"] = school.student.demographics_race_ethnicity_white
    data["Black"] = school.student.demographics_race_ethnicity_black
    data["Hispanic"] = school.student.demographics_race_ethnicity_hispanic
    data["Asian"] = school.student.demographics_race_ethnicity_asian
    data["American Indian/Alaska Native"] = school.student.demographics_race_ethnicity_aian
    data["Hawaiian Pacific Islander"] = school.student.demographics_race_ethnicity_nhpi
    data["Unknown"] = school.student.demographics_race_ethnicity_unknown
    data["Other"] = 1 - data["White"] - data["Black"] - data["Hispanic"] - data["Asian"] - data["American Indian/Alaska Native"] - data["Hawaiian Pacific Islander"] - data["Unknown"]
    data
  end

  def get_cost_data(school)
    data = {}   
    if school.cost.net_price_private_by_income_level_0_30000
      data["0-$30,000"] = school.cost.net_price_private_by_income_level_0_30000
      data["$30,001-$48,000"] = school.cost.net_price_private_by_income_level_30001_48000
      data["$30,001-$48,000"] = school.cost.net_price_private_by_income_level_30001_48000
      data["$48,001-$75,000"] = school.cost.net_price_private_by_income_level_48001_75000
      data["$75,001-$110,000"] = school.cost.net_price_private_by_income_level_75001_110000
      data["$110,001+"] = school.cost.net_price_private_by_income_level_110001_plus
    elsif school.cost.net_price_public_by_income_level_0_30000
      data["0-$30,000"] = school.cost.net_price_public_by_income_level_0_30000
      data["$30,001-$48,000"] = school.cost.net_price_public_by_income_level_30001_48000
      data["$30,001-$48,000"] = school.cost.net_price_public_by_income_level_30001_48000
      data["$48,001-$75,000"] = school.cost.net_price_public_by_income_level_48001_75000
      data["$75,001-$110,000"] = school.cost.net_price_public_by_income_level_75001_110000
      data["$110,001+"] = school.cost.net_price_public_by_income_level_110001_plus
    end
    data
  end

  def get_sat_data(school)
    school_data = {}
    school_data["Critical Reading"] = school.admission.sat_scores_midpoint_critical_reading
    school_data["Critical Reading"] = Admission.average(:sat_scores_midpoint_critical_reading)
    school_data["Math"] = school.admission.sat_scores_midpoint_math
    school_data["Writing"] = school.admission.sat_scores_midpoint_writing
    avg_data = {"Critical Reading" => 495, "Math" => 511, "Writing" => 484 }
    [{name: "#{school.school_name}", data: school_data},{ name: "National Avg", data: avg_data}]
  end

  def get_act_data(school)
    school_data = {}
    school_data["Cummulative"] = school.admission.act_scores_midpoint_cumulative
    school_data["Math"] = school.admission.act_scores_midpoint_math
    school_data["Writing"] = school.admission.act_scores_midpoint_writing
    school_data["English"] = school.admission.act_scores_midpoint_english
    
    avg_data = {"Cummulative" => 21, "Writing" => 21.3, "English" => 20.3, "Math" => 20.9 }
    [{name: "#{school.school_name}", data: school_data},{ name: "National Avg", data: avg_data}]
  end


  def get_median_debt_data(school)
    data = []
    data << [20000, school.aid.median_debt_income_0_30000 ]
    data << [50000, school.aid.median_debt_income_30001_75000]
    data << [75000, school.aid.median_debt_income_greater_than_75000]
  end
end

app/views/schools/_academics.html.erb
<h1>Academics</h1>

<table class="table table-striped">
	<tr>
		<th>Subject</th>
		<th>Percent of Students</th>
	</tr>

	<% school.popular_subjects.each do |subject, percent| %>
		<tr>
			<td><%= subject_name(subject) %></td>
			<td><%= to_percent(percent) %></td>
		</tr>
	<% end %>
</table>

app/views/schools/_admission_table.html.erb
<h1>Admissions</h1>

<table class="table table-striped">
  
  <tr>
    <td>Overall Admission Rate</td>
    <td><%= to_percent(school.admission.admission_rate_overall) %></td>
  </tr>

  <tr>
    <td>SAT - Average Overall</td>
    <td><%= float_to_int(school.admission.sat_scores_average_overall) %></td>
  </tr>

  <tr>
    <td>SAT - Critical Reading (25th - 75th Percentile)</td>
    <td><%= float_to_int(school.admission.sat_scores_25th_percentile_critical_reading) %> - 
    <%= float_to_int(school.admission.sat_scores_75th_percentile_critical_reading) %></td>
  </tr>

  <tr>
    <td>SAT - Math (25th - 75th Percentile)</td>
    <td><%= float_to_int(school.admission.sat_scores_25th_percentile_math) %> - 
    <%= float_to_int(school.admission.sat_scores_75th_percentile_math) %></td>
  </tr>

  <tr>
    <td>SAT - Writing (25th - 75th Percentile)</td>
    <td><%= float_to_int(school.admission.sat_scores_25th_percentile_writing) %> - 
    <%= float_to_int(school.admission.sat_scores_75th_percentile_writing) %></td>
  </tr>

  <tr>
    <td>ACT - Cumulative (25th - 75th Percentile)</td>
    <td><%= float_to_int(school.admission.act_scores_25th_percentile_cumulative) %> - 
    <%= float_to_int(school.admission.act_scores_75th_percentile_cumulative) %></td>
  </tr>

  <tr>
    <td>ACT - English (25th - 75th Percentile)</td>
    <td><%= float_to_int(school.admission.act_scores_25th_percentile_english) %> - 
    <%= float_to_int(school.admission.act_scores_75th_percentile_english) %></td>
  </tr>

  <tr>
    <td>ACT - Math (25th - 75th Percentile)</td>
    <td><%= float_to_int(school.admission.act_scores_25th_percentile_math) %> - 
    <%= float_to_int(school.admission.act_scores_75th_percentile_math) %></td>
  </tr>

  <tr>
    <td>ACT - Writing (25th - 75th Percentile)</td>
    <td><%= float_to_int(school.admission.act_scores_25th_percentile_writing) %> - 
    <%= float_to_int(school.admission.act_scores_75th_percentile_writing) %></td>
  </tr>

</table>

app/views/schools/_aid.html.erb
<h1>Aid</h1>


<table class="table table-striped">
<tr>
	<td>Percent of undergraduates receiving Pell Grants</td>
	<td><%= to_percent(school.aid.pell_grant_rate) %></td>
</tr>
<tr>
	<td>Percent of undergraduates receiving a federal student loan</td>
	<td><%= to_percent(school.aid.federal_loan_rate) %></td>
</tr>
</table>

<table class="table table-striped">
<caption>Median Loan Debt by family income</caption>
	<tr>
		<th>Family Income</th>
		<th>Median Loan Debt</th>
	</tr>
<tr>
	<td>$0-30,000</td>
	<td><%= number_to_currency(school.aid.median_debt_income_0_30000, precision: 0) %></td>
</tr>
<tr>
	<td>$30,001-75,000</td>
	<td><%= number_to_currency(school.aid.median_debt_income_30001_75000, precision: 0) %></td>
</tr>
<tr>
	<td>$75,000+</td>
	<td><%= number_to_currency(school.aid.median_debt_income_greater_than_75000, precision: 0) %></td>
</tr>
</table>

app/views/schools/_charts.html.erb
<div class="chart">
	<h3>Ethnicity Demographics</h3>
  <%= pie_chart(get_demographic_data(@school),  height: "400px") %>
</div>

<div class="chart">
	<h3>Midpoint SAT Scores</h3>
  <%= bar_chart( get_sat_data(@school), {library: { hMax: 800, colors: [ "green", "#78AB46"] , hAxis: {title: "Score"}, vAxis: {title: "Subject"}}} ) %>
</div>

<hr>

<div class="chart">
	<h3>Midpoint ACT Scores</h3>
  <%= bar_chart get_act_data(@school), {library: { hMax: 36, colors: [ "#ffa500", "#ffc966"], hAxis: {title: "Score"}, vAxis: {title: "Subject"}}} %>
</div>

<hr>
 
<div class="chart">
	<h3>Average Cost Per Year By Income</h3>
  <%= column_chart get_cost_data(@school), {library: { hAxis: {title: "Income Bracket"}, vAxis: {title: "Average Attendance Cost Per Year"}}} %>
</div>
<hr>
<div class="chart">
	<h3>Median Debt By Income</h3>
  <%= line_chart get_median_debt_data(@school), {library: { hAxis: {title: "Income ($)"}, vAxis: {title: "Average Amount of Debt Immediatley after Graduation ($)"}}} %>
</div>

 

app/views/schools/_completion_table.html.erb
<!-- NOTE: This partial no longer in use -->


<table class="table table-hover">
  <tbody>
    <tr>
      <th>

        <% @stats = school.completion %>
        <div class="container"><h1> <%= school.school_name %> Completions Statistics </h1>





        </div>

        <div id="completion_tabs" class="container"> 

          <ul class="nav nav-tabs">
            <li class="active"><a  href="#two_year" data-toggle="tab">Two-Year Completion Stats</a></li>
            <li><a href="#four_year" data-toggle="tab">Four-Year Completion Stats</a></li>
            <!--  <li><a href="#six_year" data-toggle="tab">Six-Year Completion Stats</a></li>
            <li><a href="#overall_six_year" data-toggle="tab">Overall Completion Stats</a></li>-->
          </ul>

          <div class="tab-content ">
            <div class="tab-pane active" id="two_year">
              <table class="table table-hover">
                <tbody>

                  <tr>
                    <td> Percent withdrawn from original institution within 2 years </td>
                    <td> <%= @stats.title_iv_withdrawn_by_2yrs || "N/A" %> </td>
                  </tr>
                  <tr>
                    <td> Percent still enrolled at original institution within 2 years </td>
                    <td> <%= @stats.title_iv_still_enrolled_by_2yrs || "N/A" %> </td>
                  </tr>
                  <tr>
                    <td> Percent of low-income (less than $30,000 in nominal family income) students who were still enrolled at original institution within 2 years </td>
                    <td> <%= @stats.title_iv_low_inc_still_enrolled_by_2yrs || "N/A" %> </td>
                  </tr>
                  <tr>
                    <td> Percent of middle-income (between $30,000 and $75,000 in nominal family income) students who were still enrolled at original institution within 2 years </td>
                    <td> <%= @stats.title_iv_mid_inc_still_enrolled_by_2yrs || "N/A" %> </td>
                  </tr>
                  <tr>
                    <td> Percent of high-income (above $75,000 in nominal family income) students who were still enrolled at original institution within 2 years </td>
                    <td> <%= @stats.title_iv_high_inc_still_enrolled_by_2yrs || "N/A" %> </td>
                  </tr>
                  <tr>
                    <td> Percent of independent students withdrawn from original institution within 2 years </td>
                    <td> <%= @stats.title_iv_independ_withdrawn_by_2yrs || "N/A" %> </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div class="tab-pane" id="four_year">
             <table class="table table-hover">
              <tbody>
                <tr>
                  <td>   Percent completed within 4 years at original institution   </td>
                  <td> <%= @stats.title_iv_completed_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>   Percent still enrolled at original institution within 4 years   </td>
                  <td> <%= @stats.title_iv_still_enrolled_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>   Percent of students who received a federal loan at the institution and who died within 4 years at original institution   </td>
                  <td> <%= @stats.title_iv_loan_recip_died_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>  Percent of students who never received a federal loan at the institution and who completed in 4 years at original institution    </td>
                  <td> <%= @stats.title_iv_no_loan_completed_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>   Percent of students who never received a federal loan at the institution and withdrew from original institution within 4 years   </td>
                  <td> <%= @stats.title_iv_no_loan_withdrawn_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>   Percent of first-generation students who died within 4 years at original institution   </td>
                  <td> <%= @stats.title_iv_first_gen_died_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>   Percent of first-generation students who completed within 4 years at original institution   </td>
                  <td> <%= @stats.title_iv_first_gen_completed_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>   Percent of first-generation students withdrawn from original institution within 4 years   </td>
                  <td> <%= @stats.title_iv_first_gen_withdrawn_by_4yrs || "N/A" %> </td>
                </tr>
                <tr>
                  <td>   Percent of first-generation students who were still enrolled at original institution within 4 years   </td>
                  <td> <%= @stats.title_iv_first_gen_still_enrolled_by_4yrs || "N/A" %> </td>
                </tr>
              </tbody>
            </table>
          </div>

          <!-- 
          <div class="tab-pane" id="six_year">

          </div>

          <div class="tab-pane" id="overall_six_year">

          </div>
           -->

        </div>

      </div>
    </th>
  </tr>
</tbody>
</table>

app/views/schools/_cost.html.erb
<h1>Cost</h1>

<table class="table table-striped">

 <caption>Tuition</caption>

  <tr>
    <td>Tuition In State</td>
    <td><%= number_to_currency(school.cost.tuition_in_state, precision:0) %></td>
  </tr>

  <tr>
    <td>Tuition Out of State</td>
    <td><%= number_to_currency(school.cost.tuition_out_of_state, precision:0) %></td>
  </tr>

</table>

<table class="table table-striped">
  <caption>Net Price (full cost minus aid) by Income Level</caption>
  
  <tr>
    <td>$0-30,000</td>
    <td><%= number_to_currency(school.cost.net_price_public_by_income_level_0_30000, precision:0) || number_to_currency(school.cost.net_price_private_by_income_level_0_30000, precision:0) %></td>
  </tr>

  <tr>
    <td>$30,001-$48,000</td>
    <td><%= number_to_currency(school.cost. net_price_public_by_income_level_30001_48000, precision:0) || number_to_currency(school.cost.net_price_private_by_income_level_30001_48000, precision:0) %></td>
  </tr>

   <tr>
    <td>$48,001-$75,000</td>
    <td><%= number_to_currency(school.cost. net_price_public_by_income_level_48001_75000, precision:0) || number_to_currency(school.cost.net_price_private_by_income_level_48001_75000, precision:0) %></td>
  </tr>

   <tr>
    <td>$75,001-$110,000</td>
    <td><%= number_to_currency(school.cost. net_price_public_by_income_level_75001_110000, precision:0) || number_to_currency(school.cost.net_price_private_by_income_level_75001_110000, precision:0) %></td>
  </tr>

   <tr>
    <td>$110,001+</td>
    <td><%= number_to_currency(school.cost. net_price_public_by_income_level_110001_plus, precision:0) || number_to_currency(school.cost.net_price_private_by_income_level_110001_plus, precision:0) %></td>
  </tr>

  

</table>

app/views/schools/_repayment.html.erb
<% @stats = school.repayment %>

<h1>Student Loan Repayment</h1>
<table class="table table-striped">
  <tbody>
    <tr>
      <td> Three-year repayment rate for completers   </td>
      <td><%= @stats.three_yr_repayment_completers %> </td>
    </tr>
    <tr>
      <td> Three-year repayment rate by family income ($0-30,000)   </td>
      <td><%= @stats.three_yr_repayment_income_0_30000.round(2) %> </td>
    </tr>
    <tr>
      <td>  Three-year repayment rate by family income ($30,000-75,000)  </td>
      <td><%= @stats.three_yr_repayment_income_30000_75000.round(2) %> </td>
    </tr>
    <tr>
      <td>  Three-year repayment rate by family income ($75,000+)  </td>
      <td><%= @stats.three_yr_repayment_income_greater_than_75000.round(2) %> </td>
    </tr>
    <tr>
      <td>   Number of students in the 5-year repayment rate of Pell students cohort </td>
      <td><%= @stats.five_yr_repayment_pell_grant %> </td>
    </tr>
    <tr>
      <td>  Number of students in the 7-year repayment rate cohort  </td>
      <td><%= @stats.seven_yr_repayment_overall %> </td>
    </tr>
    <tr>
      <td>  Number of students in the 7-year repayment rate of completers cohort  </td>
      <td><%= @stats.seven_yr_repayment_completers %> </td>
    </tr>
  </tbody>
</table>

app/views/schools/_restaurants.html.erb
<h1>Nearby Restaurants</h1>
<% restaurants.each do |restaurant| %>
  <div class="col-xs-12 col-sm-6">
    <div class="row">
      <div class="col-xs-3">
        <%= link_to restaurant.url, :target => "_blank" do %>
          <%= image_tag restaurant.image_url, class: "img-rounded img-responsive" %>
        <% end %>
      </div>
      <div class="col-xs-9" id="restaurant-info">
        <%= link_to restaurant.name, restaurant.url, :target => "_blank" %><br>
        Yelp Rating: <%= image_tag restaurant.rating_img_url %><br>
        <% if restaurant.categories != nil %>
          <% restaurant.categories.each_with_index do |category, index| %>
            <%= category[0] %><%= "," unless index == restaurant.categories.length - 1 %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/schools/_school.html.erb
<div class="well">
  <h4><%= link_to school.school_name, school_path(school.id) %></h4>
  <%= school.location %>

<% if signed_in_user? %>
  <% if bookmarked?(school) %>

     <%= button_to "Remove from Schools", school_bookmark_path(school.id, find_user_bookmark(school).id), method: :delete, class: "btn btn-success", id: "bookmark-button-index" %>

  <% else %>
   <%= button_to "Add To Schools", school_bookmarks_path(school.id), method: :post, class: "btn btn-success", id: "bookmark-button-index" %>
  <% end %>
<% end %>

</div>
<hr>

app/views/schools/index.html.erb
<h1>Your Search Results</h1>


<% @schools.each do |school| %>
	<%= render "school", school: school %>
<% end %>

app/views/schools/show.html.erb
<h1><%= @school.school_name %></h1>

<h4><%= link_to "School Website", "http://#{@school.school_school_url}", id: "school-site-link" %>
</hr><br>

  <div>

  <% if signed_in_user? %>
    <% if bookmarked?(@school) %>
       <%= button_to "Remove from MySchools", school_bookmark_path(@school.id, find_user_bookmark(@school).id), method: :delete, class: "btn btn-success", id: "bookmark-button" %> 
    <% else %>
     <%= button_to "Add to MySchools", school_bookmarks_path(@school.id), method: :post, class: "btn btn-success", id: "bookmark-button" %>
    <% end %>

    <%= link_to "See School Reviews", school_reviews_path(@school.id), class: "btn btn-primary", id: "see-reviews-button" %>

  <% end %>

 </div>

  <br>

	<%= image_tag @school.get_street_view, class: "img-rounded" %>

	<%= image_tag @school.get_map_url, class: "img-rounded" %><br>

<br>

<div id="exTab2">
<ul class="nav nav-tabs">
			<li class="active"><a  href="#overall" data-toggle="tab">Overall</a></li>

			<li><a href="#academics" data-toggle="tab">Academics</a></li>

			<li><a href="#admissions" data-toggle="tab">Admissions</a></li>
      <li><a href="#students" data-toggle="tab">Students</a></li>
			<li><a href="#aid" data-toggle="tab">Aid</a></li>
			<!-- <li><a href="#completion" data-toggle="tab">Completion</a></li> -->
			<li><a href="#cost" data-toggle="tab">Cost</a></li>
			<!-- <li><a href="#earnings" data-toggle="tab">Earnings</a></li> -->
			<!--<li><a href="#repayment" data-toggle="tab">Repayment</a></li>-->
      <li><a href="#restaurants" data-toggle="tab">Nearby Restaurants</a></li>

		</ul>

			<div class="tab-content ">
			  <div class="tab-pane active" id="overall">
          <%= render "school_table", school: @school %>
          <%= render "charts", school: @school %>
          <hr></hr>
				</div>

				<div class="tab-pane" id="academics">
          <%= render "academics", school: @school %>
				</div>

				<div class="tab-pane" id="admissions">
          <%= render "admission_table", school: @school %>
				</div>

        <div class="tab-pane" id="aid">
          <%= render "aid", school: @school %>
				</div>

				 <div class="tab-pane" id="cost">
          <%= render "cost", school: @school %>
				</div>

				<!--<div class="tab-pane" id="repayment">
          <%#= render "repayment", school: @school %>
				</div>-->

				<div class="tab-pane" id="students">
          <%= render "student_table", school: @school %>
				</div>

        <div class="tab-pane" id="restaurants">
          <%= render "restaurants", restaurants: @restaurants %>
        </div>


			</div>
  </div>
<%= render "shared/footer" %>