config/routes.rb
Rails.application.routes.draw do



  root "users#index"

  resources :users do 
    resources :reviews, :only => [:index, :show]
  end

  resources :schools do 
    resources :reviews
    resources :bookmarks, only: [:create, :update, :destroy]
  end

  resource :session, :only => [:new, :create, :destroy]
  resources :schools, only: [:index, :show]
  resources :comparisons, :only => [:index]

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"


end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-dark bg-primary">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">App.ly</a>
  </div>

  <div class="navbar-collapse collapse" id="navbar">
    <form action="/session" method="post" class="navbar-form navbar-right" >
      <input name="utf8" type="hidden" value="✓">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
      <div class="form-group">
        <input type="text" name="email" placeholder="Email" class="form-control">
      </div>
      <div class="form-group">
        <input type="password" name="password" placeholder="Password" class="form-control">
      </div>
      <input type="submit" value="Log In" class="btn btn-primary">
    </form>
  </div>

</nav>

app/views/layouts/_navbarlogin.html.erb
<nav id="login_nav" class="navbar navbar-fixed-top navbar-dark bg-primary">

  <div class="container">
    <div class="row">

      <div class="col-xs-3">
        <div class="logo-container">
          <%= link_to "App.ly", root_path, class: "navbar-brand" %>
        </div>
      </div>

      <div class="col-xs-4 col-xs-offset-1">
        <div class="search-container">
          <div class="form-group pull-left form-inline">
            <%= form_tag schools_path, :method => 'get' do %>
              <%= text_field_tag "query[school_name]", nil, placeholder: "School Name", class: "form-control" %>
              <%= submit_tag "Search", class: "form-control" %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-xs-4">
        <div class="name-container">
          <p class="pull-right">
            <%= link_to "MySchools", user_path(current_user), style: "color: white" %> | 
            <%= link_to "Logout", logout_path, style: "color: white" %>
              
          </p>

        </div>
      </div>

    </div>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App.ly</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/flatly/bootstrap.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="http://www.cde.ca.gov/favicon.ico" />
</head>
<body data-no-turbolinks class="container app-body">

  <%= navbar %>

  <br><br><br><br>

   <% flash.each do |type, message| %>
      <div class="alert alert-<%= "#{type}" %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>

  <%= yield %>

</body>
</html>